num1=int(input('enter first number: '))
num2=int(input('enter the second number: '))
print('num1 & num2= ',num1&num2)
print('\n num1|num2= ',num1|num2)
print('\n ~num1= ',~num1)
print('\n num1^num2= ', num1^num2)
print('\n num1>>1', num1>>1)
print('\n num2<<1', num2<<1)